FROM openjdk:11

RUN apt-get update && apt-get install -y git python3 vim

RUN git clone https://github.com/pavel-collab/SBT-DevOpsHT.git

WORKDIR /DevOpsHometask/Lab02/

RUN get checkout Lab02

RUN echo 172.18.0.3 > app/ip