FROM ubuntu:20.04

# we have to install and setup ssh-server and python to be able connect from ansible host
RUN apt-get update && apt-get -y install openssh-server supervisor
RUN apt-get install python3
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config