version: "3.7"

services:

  server:
    container_name: server
    image: default_host_image
    restart: unless-stopped
    networks:
      local_network:
        ipv4_address: 172.18.0.2

  client:
    container_name: client
    image: default_host_image
    restart: unless-stopped
    networks:
      local_network:
        ipv4_address: 172.18.0.3

  ansible:
    container_name: ansible
    image: ansible_image
    command: ansible-playbook -v -i inventories/hosts playbook.yml
    restart: "no"
    networks:
      local_network:
        ipv4_address: 172.18.0.5

networks:
  local_network:
    driver: bridge
    name: local_network
    ipam:
      config:
        - subnet: 172.18.0.0/16