FROM ubuntu:20.04

RUN apt-get update && apt-get install -y git python3 vim

RUN git clone https://github.com/pavel-collab/SBT-DevOpsHT.git

WORKDIR /SBT-DevOpsHT/Lab02//Lab02/

RUN git checkout Lab02