---
- name: Hosts setting up
  hosts: hosts
  become: true
  tasks:
    - name: DEBUG ping
      ping:
      register: ping_result

    - name: Update system
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Install python
      raw: apt install -y python3
    
    - name: Install git
      raw: apt install git
    
    - name: Install application
      raw: git clone https://github.com/pavel-collab/SBT-DevOpsHT.git && cd SBT-DevOpsHT && git checkout Lab02

- name: Server setup & running
  hosts: server
  gather_facts: false
  roles:
    - server
  become: true

- name: Client setup & running
  hosts: client
  gather_facts: false 
  roles:
    - client
  become: true