---
- name: Hosts setting up
  hosts: hosts
  become: false
  tasks:
    - name: ping all serveses
      ping:
      register: ping_result

- name: Server setup & running
  hosts: server
  gather_facts: false
  roles:
    - server
  become: true

- name: Client setup & running
  hosts: client
  gather_facts: false 
  roles:
    - client
  become: true