apiVersion: v1
kind: Service
metadata:
  name: my-flask-app
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000  # Укажите желаемый NodePort
  selector:
    app: my-flask-app