version: '3.8'

#TODO: добавить restart политику
services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main_db
    ports:
      - "5432:5432" # согласно документации (см postgresql.conf) postgresql работает именно на порту 5432 (by default)
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: flask_app
    container_name: flask_app
    command: flask run --host=0.0.0.0 --port=8080
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/main_db
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:

#TODO: добавить формальное описание сети